In [1]:
import os 
import sys 
import pandas as pd
from IPython.display import display

In [2]:
data_dir = "/Users/Jackie/Work/RecommendationSystem/data/ml-1m"

In [3]:
def get_data(base_dir, filename, columns):
    with open(os.path.join(base_dir, filename) , 'r') as infile:
        data = infile.readlines()
        df = pd.DataFrame([row.rstrip().split('::') for row in data], columns=columns)
    return df 

In [4]:
movies = get_data(data_dir, "movies.dat", 'MovieID::Title::Genres'.split("::"))
ratings = get_data(data_dir, "ratings.dat", "UserID::MovieID::Rating::Timestamp".split("::"))
users = get_data(data_dir, "users.dat", "UserID::Gender::Age::Occupation::Zip-code".split("::"))

In [5]:
display(movies.head())
display(ratings.head())
display(users.head())

MovieID                               Title                        Genres
0       1                    Toy Story (1995)   Animation|Children's|Comedy
1       2                      Jumanji (1995)  Adventure|Children's|Fantasy
2       3             Grumpier Old Men (1995)                Comedy|Romance
3       4            Waiting to Exhale (1995)                  Comedy|Drama
4       5  Father of the Bride Part II (1995)                        Comedy

UserID MovieID Rating  Timestamp
0      1    1193      5  978300760
1      1     661      3  978302109
2      1     914      3  978301968
3      1    3408      4  978300275
4      1    2355      5  978824291

UserID Gender Age Occupation Zip-code
0      1      F   1         10    48067
1      2      M  56         16    70072
2      3      M  25         15    55117
3      4      M  45          7    02460
4      5      M  25         20    55455

In [99]:
ratings_test = pd.DataFrame()
for k, v in ratings.groupby('UserID'):
    ratings_test = ratings_test.append(v.sample(frac = 0.2))
ratings_train = pd.merge(ratings, ratings_test, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)    

In [114]:
list(ratings_test['MovieID'].unique())

['1',
 '783',
 '2687',
 '2804',
 '2321',
 '594',
 '2355',
 '2791',
 '1721',
 '2797',
 '2018',
 '745',
 '3108',
 '3252',
 '1307',
 '2640',
 '954',
 '3259',
 '2000',
 '2111',
 '339',
 '3471',
 '277',
 '3296',
 '969',
 '2140',
 '110',
 '1947',
 '2294',
 '1234',
 '3095',
 '1257',
 '3869',
 '2497',
 '1967',
 '1639',
 '1441',
 '2137',
 '2',
 '830',
 '588',
 '329',
 '2826',
 '3675',
 '916',
 '3751',
 '351',
 '2874',
 '3438',
 '2571',
 '1948',
 '671',
 '653',
 '780',
 '2622',
 '1243',
 '2033',
 '3668',
 '720',
 '2324',
 '765',
 '2628',
 '2501',
 '368',
 '333',
 '186',
 '1247',
 '1240',
 '3671',
 '2049',
 '597',
 '1073',
 '1394',
 '926',
 '1127',
 '2529',
 '1252',
 '253',
 '3868',
 '2040',
 '3114',
 '3608',
 '1513',
 '1831',
 '1682',
 '1016',
 '1080',
 '3501',
 '1088',
 '1200',
 '2535',
 '1213',
 '592',
 '1586',
 '2028',
 '1408',
 '1198',
 '2409',
 '2527',
 '858',
 '349',
 '2115',
 '480',
 '1374',
 '527',
 '377',
 '2080',
 '2990',
 '3068',
 '3418',
 '589',
 '3153',
 '3527',
 '3702',
 '1299',
 '

In [7]:
import sys
sys.path.insert(0, "/Users/Jackie/Work/github/lkpy")

In [8]:
from lenskit.datasets import ML100K
from lenskit import batch, topn, util
from lenskit import crossfold as xf
from lenskit.algorithms import Recommender, als, item_knn as knn
from lenskit import topn

In [17]:
import random

In [20]:
random.choice(list(dict(a=1,b=2).keys()))

'a'

In [21]:

import numpy as np

In [30]:
np.concatenate([np.random.random(5) ,np.random.random(5)]) 

array([0.98354029, 0.16717643, 0.61552068, 0.95001587, 0.30444344,
       0.34243305, 0.77958253, 0.15811742, 0.15826468, 0.07545577])

In [27]:
np.random.random(5)

array([0.55878703, 0.65540141, 0.17798379, 0.54374766, 0.45205516])

In [116]:
ratings.set_index(['UserID', 'MovieID'])['Rating'].to_dict()

{('1', '1193'): '5',
 ('1', '661'): '3',
 ('1', '914'): '3',
 ('1', '3408'): '4',
 ('1', '2355'): '5',
 ('1', '1197'): '3',
 ('1', '1287'): '5',
 ('1', '2804'): '5',
 ('1', '594'): '4',
 ('1', '919'): '4',
 ('1', '595'): '5',
 ('1', '938'): '4',
 ('1', '2398'): '4',
 ('1', '2918'): '4',
 ('1', '1035'): '5',
 ('1', '2791'): '4',
 ('1', '2687'): '3',
 ('1', '2018'): '4',
 ('1', '3105'): '5',
 ('1', '2797'): '4',
 ('1', '2321'): '3',
 ('1', '720'): '3',
 ('1', '1270'): '5',
 ('1', '527'): '5',
 ('1', '2340'): '3',
 ('1', '48'): '5',
 ('1', '1097'): '4',
 ('1', '1721'): '4',
 ('1', '1545'): '4',
 ('1', '745'): '3',
 ('1', '2294'): '4',
 ('1', '3186'): '4',
 ('1', '1566'): '4',
 ('1', '588'): '4',
 ('1', '1907'): '4',
 ('1', '783'): '4',
 ('1', '1836'): '5',
 ('1', '1022'): '5',
 ('1', '2762'): '4',
 ('1', '150'): '5',
 ('1', '1'): '5',
 ('1', '1961'): '5',
 ('1', '1962'): '4',
 ('1', '2692'): '4',
 ('1', '260'): '4',
 ('1', '1028'): '5',
 ('1', '1029'): '5',
 ('1', '1207'): '4',
 ('1', '20

In [48]:
ratings[ratings.UserID=='4169']

UserID MovieID Rating  Timestamp
695642   4169    3789      5  965333672
695643   4169     571      4  973310265
695644   4169     574      3  975805232
695645   4169     575      3  976589949
695646   4169     577      3  988324145
...       ...     ...    ...        ...
697951   4169    3784      2  965333606
697952   4169    3785      3  980476924
697953   4169    2047      3  971579815
697954   4169    3788      3  965333481
697955   4169    2049      3  965693586

[2314 rows x 4 columns]

In [53]:
np.random.normal(size= (10, 2))

array([[-0.75463588,  0.49401592],
       [ 0.38362179, -1.39348633],
       [ 0.43939364,  1.23191413],
       [-1.46610787,  0.06988827],
       [-0.80200301, -0.90017399],
       [-1.61928952, -0.91155282],
       [ 1.01250429, -1.18061018],
       [ 0.1831965 ,  0.68101163],
       [ 0.61349651, -1.45508822],
       [-1.14290754,  1.72427753]])

In [54]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
np.sum(np.square([[2, 3], [1, 1] ]))

15

In [112]:
d = {'a' : 1}
print(d.get('b', []))

[]


In [64]:
import numpy as np                                                                                   
from scipy import linalg                                                                            
from scipy.sparse import linalg as slinalg                                                           

x = np.array([[1,1,0,0,0],[0,0,1,1,0],[1,1,1,1,1]],dtype=np.float64) # 3 x 5 

In [65]:
npsvd = np.linalg.svd(x)                                                                             
spsvd = linalg.svd(x)                                                                                
sptop = slinalg.svds(x,k=2) 

In [70]:
print("np")
print("u: ", npsvd[0])
print("s: ", npsvd[1])                                                                               
print("v: ", npsvd[2])

print("\n=========================\n")

print("sp")                                                                                           
print("u: ", spsvd[0])
print("s: ", spsvd[1])                                                                               
print("v: ", spsvd[2])

print("\n=========================\n")

print("sp top k")                                                                                     
print("u: ", sptop[0])
print("s: ", sptop[1])                                                                               
print("v: ", sptop[2])


nptmp = np.zeros((npsvd[0].shape[1],npsvd[2].shape[0]))                                              
nptmp[np.diag_indices(np.min(nptmp.shape))] = npsvd[1]                                               
npreconstruct = np.dot(npsvd[0], np.dot(nptmp,npsvd[2]))                                             

print(npreconstruct)                                                                                  
print("np close? : ", np.allclose(npreconstruct, x))                                                  

sptmp = np.zeros((spsvd[0].shape[1],spsvd[2].shape[0]))                                              
sptmp[np.diag_indices(np.min(sptmp.shape))] = spsvd[1]                                               
spreconstruct = np.dot(spsvd[0], np.dot(sptmp,spsvd[2]))                                             

print(spreconstruct)                                                                                  
print("sp close? : ", np.allclose(spreconstruct, x))                                                  

sptoptmp = np.zeros((sptop[0].shape[1],sptop[2].shape[0]))                                           
sptoptmp[np.diag_indices(np.min(sptoptmp.shape))] = sptop[1]                                         
sptopreconstruct = np.dot(sptop[0], np.dot(sptoptmp,sptop[2]))                                       

print(sptopreconstruct)                                                                               
print("sp top close? : ", np.allclose(sptopreconstruct, x))

np
u:  [[-3.64512933e-01  7.07106781e-01 -6.05912800e-01]
 [-3.64512933e-01 -7.07106781e-01 -6.05912800e-01]
 [-8.56890100e-01  3.33066907e-16  5.15499134e-01]]
s:  [2.58873755 1.41421356 0.54629468]
v:  [[-4.71814160e-01 -4.71814160e-01 -4.71814160e-01 -4.71814160e-01
  -3.31006941e-01]
 [ 5.00000000e-01  5.00000000e-01 -5.00000000e-01 -5.00000000e-01
  -1.11022302e-16]
 [-1.65503471e-01 -1.65503471e-01 -1.65503471e-01 -1.65503471e-01
   9.43628319e-01]
 [ 5.00000000e-01 -5.00000000e-01 -5.00000000e-01  5.00000000e-01
  -2.22044605e-16]
 [-5.00000000e-01  5.00000000e-01 -5.00000000e-01  5.00000000e-01
   2.22044605e-16]]


sp
u:  [[-3.64512933e-01  7.07106781e-01 -6.05912800e-01]
 [-3.64512933e-01 -7.07106781e-01 -6.05912800e-01]
 [-8.56890100e-01  3.33066907e-16  5.15499134e-01]]
s:  [2.58873755 1.41421356 0.54629468]
v:  [[-4.71814160e-01 -4.71814160e-01 -4.71814160e-01 -4.71814160e-01
  -3.31006941e-01]
 [ 5.00000000e-01  5.00000000e-01 -5.00000000e-01 -5.00000000e-01
  -1.11022302

In [75]:
pred = np.array([[2, 3], [1, 1], [0, 1] ])[:, 1]
actual = np.array([[2, 3], [1, 1], [0, 1] ])[:, 0]

In [79]:
np.mean((pred - actual) ** 2) 

0.6666666666666666

In [77]:
actual

array([2, 1, 0])

In [80]:
{1, 2} & {2, 3}

{2}

In [1]:
a = [2, 3, 4, 5]

In [4]:

res = a[-3:].reverse()

In [8]:
a[-3:]

[3, 4, 5]

In [10]:
a.reverse()

In [11]:
a

[5, 4, 3, 2]

In [13]:
import itertools

In [15]:
timer = itertools.count(step=-1)

In [24]:
type(timer)

itertools.count

In [25]:
def count(start=0, step=1):
    # count(10) --> 10 11 12 13 14 ...
    # count(2.5, 0.5) -> 2.5 3.0 3.5 ...
    n = start
    while True:
        yield n
        n += step

In [49]:
c= count()

In [97]:
tweets = {'a': [1,3, 5, 7, 9 ], 'b': [2, 4, 6, 8, 10, 12]}

In [99]:
import heapq
tmp = (tweets[u] for u in ['a', 'b'])
tmp2 = heapq.merge(*tmp)
#[e for e in itertools.islice(tmp2, 5)]

In [100]:
list(tmp2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12]

[1, 2, 3, 4, 5]

In [ ]:
[22, 333, 505, 94, 2, 10, 13, 101, 3, 5]